### ISSUE TITLE
Feature: Add link to open issue in this repo at the bottom of Zendesk Ticket

### ISSUE THREAD

**Issue by teakopp** [GitHub-IT-Ops/Issuedesk#19]
Add message at the bottom of ticket, stating something like "Created by Issuedesk (link to this repo) Experiencing trouble? Open an issue here (link to new issue in this repo). This feature is important because users will know where to report bugs.

**Comment by teakopp** [comment]
@cholesterol made this happen with this [PR](https://github.com/GitHub-IT-Ops/Issuedesk/pull/26)

**Comment by Cholesterol** [comment]
closing with extreme prejudice
